### PR TITLE
Lerna build  (WIP PR)

### PR DESCRIPTION
**Pull request by mul1sh**
This is a WIP PR to fix the issue #107  thanks 🙂

### CODE REVIEW

**Comment by raulk** [comment]
Hey, thanks for the clarification. I realised that using lerna introduces a `package-lock.json`. We are using yarn instead of npm. Any way to integrate lerna with yarn, or should we use yarn workspaces instead?

BTW - even if #106 is not ready yet, you could start configuring the build for the `core` and `erc20` modules.

**Comment by mul1sh** [comment]
@raulk thanks for the feedback, i'll get started then. As for the yarn integration, yes we'll use workspaces, in fact `lerna` already supports this integration by [passing the flag](https://github.com/lerna/lerna/tree/master/commands/bootstrap#--use-workspaces) `--use-workspaces` when bootstrapping a new lerna project.

**Comment by raulk** [comment]
@mul1sh any progress here?

**Comment by mul1sh** [comment]
@raulk yes, pushing in abit

**Comment by raulk** [comment]
Closing this PR as there has been no progress and the feedback has not been addressed yet. @mul1sh, let's continue discussing how to move forward in the bounty issue #107.

**Pull request closed without merging**
