### PR TITLE
Lerna build (WIP PR)

### LINKED ISSUE #107: Lerna build
## Motivation

We want to publish each plugin independently on NPM, so that users can compose only the plugins they require in their deployment. Independent versioning of plugins may also be desirable.

## Requirements

- [x] Configure the build to use [lerna](https://github.com/lerna/lerna).
- [x] Each plugin should be enclosed in a separate package, with the exception of `core`, which should be part of the engine.
- [x] Resulting Node packages:
  * ethql => foundation + core plugin
  * ethql-erc20
  * ethql-ens (see #106)
- [x] Help us decide if we want independent module versioning, or not. Argument for and against.
- [x] This issue should be resolved after #106, so that we have at least 3 packages.
- [x] **do not publish anything on NPM just yet, we will do that from the ConsenSys organisation**.

## Definition of done

- [x]  PR accepted and merged, including all changes to `package.json`, directory layout, etc. to implement the above requirements.
- [ ] Updated README and wiki pages: particularly "how to build" instructions, and "usage/install" sections.
- [ ] Good discussion with a decision regarding independent versioning or not.

### PR DESCRIPTION
**Pull request by mul1sh**
In this PR i've started splitting out the plugins, so next i'll add the package.json files for each of the seperate pacakages/plugins as recommended by [lerna](https://github.com/lerna/lerna#lernajson)

Fixes #107

### CODE REVIEW

**Comment by raulk** [comment]
@mul1sh slight change in naming, this should be the directory structure:

```
packages
  |___ base
  |___ core-plugin
  |___ erc20-plugin
  |___ ens-plugin
  |___ erc721-plugin
  |___ ...
```

In the package.json, the package names should be preceded with `@ethql`, ie. `@ethql/core-plugin`, `@ethql/base`, etc.

Please provide an exact date when this issue will be finished ;-) Thanks.

**Comment by mul1sh** [comment]
@raulk thanks for the feedback 🙂  will implement it like this. As for the exact date for finishing this issue, I plan to finish it by this coming Friday end of day.

**Comment by mul1sh** [comment]
@raulk just a question before I make another commit, what files should go into base, core and  erc721-plugin?

Also I can see the ens module is still not done, so how do i address the `ens-plugin` part? Thanks.

**Comment by raulk** [comment]
@mul1sh Everything that is not a plugin should go in base. The `core` directory contains a plugin, and should end up in `core-plugin`. The erc721 plugin is not ready yet, I think you mean the erc20 plugin?

Regarding `ens-plugin`, @StevenJNPearce should be able to help you there!

**Comment by mul1sh** [comment]
@raulk awesome thanks for the clarification, let me reach out to @StevenJNPearce  then and wrap up whats left

**Comment by raulk** [comment]
@mul1sh We haven't heard from you in the last 2 weeks. We need to make progress a bit faster, so we will be putting this bounty up for grabs on Gitcoin again. Thank you.

**Comment by mul1sh** [comment]
@raulk sorry for the delay, I was still waiting for the ens plugin so that i wrap everything at once. Anyway no worries I understand

**Pull request closed without merging**
