### PR TITLE
Introduce the concept of 'entity' in decoded TX

### LINKED ISSUE #58: Decoded transactions should refer to classes/entities rather than standards
ethql should refer to _classes or entities_ rather than specific standards. For example, all of ERC20, ERC223, ERC827 relate to **tokens**. 

It is sometimes unfeasible (or hardly worthwhile) to distinguish exactly which standards a given contract implements (although it could be achieved if the contract implements ERC165, or by inspecting the bytecode). Users are generally concerned with the underlying entity.

In the future we might introduce "standards inference" as a functionality, but for now that's not the goal.

Tasks:
- [ ] Remove all schema references to ERC20 and replace them with Token.
- [ ] 'standard' as a field should disappear in favour of 'class' = 'token'.
- [ ] The TX decoder for ERC20 should be renamed to TokenTxDecoder.

In the future, we'll introduce a NonFungibleTokenTxDecoder, in #33.

### PR DESCRIPTION
**Pull request by raulk**
An entity groups related ERC standards, providing an abstraction on what kind of concept they refer to. In this way, different token interfaces can co-exist while making it easy to filter for all token transactions in a block, regardless of the underlying ERC interface (e.g. ERC20, ERC777 or ERC20+ERC777).

Altogether, I've decided against my original proposal of removing ERC20 nomenclature from types. Reading [ERC820](https://github.com/ethereum/EIPs/issues/820), made me realise that the differentiation is important when queries refer to transactions and logs, both of which adhere to a concrete ABI. 

In fact, ERC820 makes the ERC number a first-class citizen in the registry, as keys take the form `ERC20Token`, `ERC777Token`, etc. 

For me it was important to realise that some ERC introduce entities (e.g. ERC20), while others extend or alter those entities (ERC223). Those changes could impact the ABI or not. In the case of ERC223, it has no bearing on the ABI.

I've added a `README.md` in the `abi` directory to serve as a registry of all ABIs we support, and how we regard them. 

Resolves #58.

### CODE REVIEW

**Comment by raulk** [comment]
@pcardune – would appreciate your feedback here!

**Comment by jaycenhorton** [comment]
I very much support keeping erc nomenclature. Nori is a heavy consumer of 820

**Comment by pcardune** [comment]
I like this direction.

**Comment by raulk** [comment]
@pcardune @jaycenhorton – thanks for the feedback. I'm currently working on #59 which will add log decoding support shortly. Once that is in place, I'm resuming #44 because I'm solidifying a proposal in my head that I think meets all expectations.

**Comment by raulk** [comment]
Positive feedback received from the community. Merging.

**Pull request merged**
