### PR TITLE
Fix selection of block by tag

### PR DESCRIPTION
**Pull request by pcardune**
Previously we were passing web3.eth.getBlock("LATEST") when the web3 api dictates
that the tag should be lowercase: web3.eth.getBlock("latest")

### CODE REVIEW

**Comment by raulk** [comment]
Hey @pcardune, thank you for your contribution! It's great that you're helping us build ethql since these early stages.

Thanks for noticing this issue, and adding a test. I've pushed some significant refactoring in the last hours which causes a conflict.

I've already fixed the conflict, but I can't push the commits to your branch. Could you please allow commits by maintainers in your PR? Instructions: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

The changes [are here](https://github.com/raulk/ethql/tree/pcardune-fix-blog-by-tag), but I much rather push them to your PR branch. Credit where it's due! ;-)

**Comment by pcardune** [comment]
I went to turn it on and it is already checked:
image

In any case, I've gone ahead and merged master into my branch so it should be good to go now.

**Comment by pcardune** [comment]
We are interested in using ethql for [Nori](https://nori.com) and would be willing to help get it to production quality. What's the best way for us to get involved with ethql development beyond fixing bugs that we encounter?

**Comment by raulk** [comment]
LGTM. Congrats on landing your first contribution to ethql, @pcardune! Look forward to many more.

Thanks for the offer to become further involved! Could you please shoot me an email to raul.kripalani@consensys.net?

**Pull request merged**
